version: "3.9"
services:
  backend:
    image: common-assessment-tool-app
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    environment:
      - PYTHONUNBUFFERED=1

