name: CI/CD Pipeline

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run linters
        run: |
          # Run pylint with common warnings disabled
          pylint --disable=C0111,C0103,C0303,W0718,trailing-whitespace,broad-exception-caught --ignore-patterns=test_.*?py --recursive=y . || exit 0

      - name: Run Tests
        run: |
          python -m pytest tests/

  deploy:
    needs: test # This ensures deploy only runs if tests pass
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t common-assessment-tool .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 common-assessment-tool
          sleep 10  # Wait for container to start

      - name: Test Docker container
        run: |
          curl http://localhost:8080/docs
