name: Deploy to Cloud Run

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and deploy to Cloud Run
        run: |
          # Build and push Docker image to Google Container Registry
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/commonassessmenttool
          
          # Deploy to Cloud Run
          gcloud run deploy commonassessmenttool \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/commonassessmenttool \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated